DELETE http://localhost:3001/api/notes/
###
GET http://localhost:3001/api/notes/
###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
  "content": " Deepanjali's note",
  "important": false,
  "userId": "67b35a195e47d27ec7e9ade6"
}

###
PUT http://localhost:3001/api/notes/1
Content-Type: application/json

{
  "content": "This is my updated note",
  "important": true
}

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
  "username": "Deeps",
  "name": "Deepa here",
  "password": "pwddsjhbf"  
}
